### ISSUE TITLE
Hitting a break point results in renderer timing out / debugging broken

### ISSUE THREAD

**Issue by PerMalmberg** [Unity-Technologies/vscode-unity-debug#147]
Hi,

First time trying Unity and I'm having an issue with debugging scripts. Specifically, I'm getting the following error when when starting a debug run by pressing the "Start debugging" button in VS Code to attach to the Unity Editor:

> 
> 2019-12-02 23:13:27.784] [renderer1] [error] timeout after 500 ms: Error: timeout after 500 ms
> 
> at t.RawDebugSession.handleErrorResponse (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798:1003)
> at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798:434
> at async t.RawDebugSession.shutdown (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2796:536)

This is the output from the console. It looks as if it attaches, but then times out?

> UnityDebug: Initializing
> UnityDebug: Searching for Unity process 'Unity Editor'
> UnityDebug: Attached to Unity process 'Unity Editor (Unity)' (14608)

I'm running Unity and VSCode as a regular user.
I've tried restarting both Unity and VS Code but the error remains.

The VS Code extension seems to be the cause based on the conclusions in this thread:
https://forum.unity.com/threads/debugging-in-vscode-results-in-error.787196/#post-5246528

System info:

System:
Pop_OS! 19.10

VSCode Unity plugin 2.7.2

Unity:
Version 2019.3.0f1 (ffacea4b84e7) Personal
Fri, 22 Nov 2019 03:55:52 GMT
Branch: 2019.3/staging

VSCode:
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-22-generic

**Comment by marcinwalus** [comment]
Hi,
as I described in mentioned Unity Forum thread I have the same problem on macOS.

**Comment by marcinwalus** [comment]
Hmmm... this issue seems to be a duplicate of [#145](https://github.com/Unity-Technologies/vscode-unity-debug/issues/145)

**Comment by PerMalmberg** [comment]
> Hmmm... this issue seems to be a duplicate of [#145](https://github.com/Unity-Technologies/vscode-unity-debug/issues/145)
Quite the opposite, my breakpoints are actually hit.
