### ISSUE TITLE
Unity Debbuger not appears on the environment list

### ISSUE THREAD

**Issue by Neves97** [Unity-Technologies/vscode-unity-debug#161]
When trying to create an launch.json file in the environment list, a Unity Debbuger is not displayed

## Expected Behavior

The unity debbuger show on the list of environment 

## Current Behavior

nothing appears

## Steps to Reproduce (for bugs)

1. Install Debbuger for Unity 2.7.3 and OmniSharp 1.21.14
2.Open on Unity and load a script
3.Create  a launch.json file

## Your Environment
* Unity Version: 2018.4.15
* VS Code Version: 1.43.0
* Version of the debugger tool: 2.7.3 
* Operating System and version: windows 10

**Comment by aivantuquero** [comment]
Apparently, c# updated their extension id from `ms-vscode.csharp` to `ms-dotnettools.csharp`

https://github.com/OmniSharp/omnisharp-vscode/issues/3620#issuecomment-595458417

**Comment by ganaware** [comment]
I think the Unity.unity-debug-2.7.3.vsix does not contains necessary node modules.

## Error Log

The VSCode complains in the OUTPUT of Log (Extension Host) that:

```
[2020-03-16 13:40:01.499] [exthost] [error] Activating extension Unity.unity-debug failed due to an error:
[2020-03-16 13:40:01.503] [exthost] [error] Error: Cannot find module 'vscode-nls'
Require stack:
- %USERPROFILE%\.vscode\extensions\unity.unity-debug-2.7.3\out\attach.js
- %LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- %LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- %LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:849:718)
	at Function.i._load (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:628)
	at Function.n._load (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:815:969)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:524)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\unity.unity-debug-2.7.3\out\attach.js:4:11)
	at Module.o._compile (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:849:718)
	at Function.i._load (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:819:628)
	at Function.n._load (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:815:969)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:32:963)
	at d._loadCommonJSModule (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:820:773)
	at d._doActivateExtension (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:720:856)
	at d._activateExtension (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:719:841)
	at Object.actualActivateExtension (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:717:796)
	at d._activateExtension (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:522:206)
	at %LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:521:900
	at Array.map (<anonymous>)
	at d._activateExtensions (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:521:888)
	at d.activateById (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:519:931)
	at d._activateById (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:718:611)
	at d.$activate (%LOCALAPPDATA%\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:727:308)
```

## My workaround

1. install [Node.js](https://nodejs.org/en/)
2. run <code>npm install</code> in the extension directory

```cmd
> cd %USERPROFILE%
> cd .vscode\extensions\unity.unity-debug-2.7.3
> npm install
```

**Comment by miniwolf** [comment]
I have moved the dependency from dev-dependency to user dependency. If you update to 2.7.4 does that solve the problem?

**Comment by Neves97** [comment]
Well, now the debbuger appears on the list, but i the editor freezes

**Comment by ganaware** [comment]
For a small experimental project, 2.7.4 works well.
I can inspect a class field when the program is stopped at a breakpoint.

But for a large project, nothing is good.
The intellisense does not work.
The debugging does not start.

**Comment by miniwolf** [comment]
There are some people reporting that there is a regression between VSCode version 1.42.1 and 1.43.2, can you verify if this solves your problem?

**Comment by yaxamie** [comment]
Hey guys!  I'm trying to switch as well.  I've installed the latest mono on MacOS, restarted, and switched over to "always" use global mono in settings (which resolved and sdk issue I was seeing).  However, I'm unable to see an option to debug in VSCode.  Unity is able to open the project, but where most screenshots show a debugging button, I simply have a "Run" option in the sidebar.  I tried deleting the .vscode folder and restarting Unity.  I noticed that opening a script file with double-click does not regenerate .vscode but right-clicking and saying "open C# project does".  Regardless... it only seems to generate settings.json.  It doesn't seem to make launch.json.

Is this an issue with v2.7.5?  Should I try manually installing the latest somehow?

**Comment by yaxamie** [comment]
Spent a couple of hours and resolved my issue by a few steps.  Perhaps a common troubleshooting section would be in order.

1.  Uninstalled *most* plugins from VSCode.  
2.  Regererated project files in Unity
3.  Told Unity in preferences to use "Code" as the Image Application
4.  Switched to system mono in Code's preferences
5.  Manually created launch.json with the button under the "Run" options.

**Comment by danilofaugusto** [comment]
@yaxamie You're a legend, it worked for me, thanks! I've executed steps 2 to 5.

**Comment by imthiazh** [comment]
@yaxamie Thanks... I did steps 2-5 and it worked just fine. I have an assignment on this due the day after tmrw and I was stuck.

**Comment by acron0** [comment]
@yaxamie Please could you elaborate on your workaround?
How do I "Switched to system mono in Code's preferences"?
What do I put into launch.json if creating it manually?

**Comment by alexcraneunity** [comment]
@yaxamie @danilofaugusto Here to second @acron0 's comment, would you mind sharing the contents of your launch.json that you created manually? 
I'm running into this same issue. The Unity Debugger option for the environment when setting up debug options does not reliably appear, and when it does, clicking it doesn't create a launch.json - it seems to just fail.

**Comment by MichaelHighsmith** [comment]
@acron0  @alexcraneunity  I just encountered this same issue and @yaxamie 's solution works. To switch to mono you need to go to File -> Preferences -> Settings. In Settings search for 'mono' at the top and then change Omnisharp: Use Global Mono from 'auto' to 'always'. After doing this you can click the debug tool on the left bar and generate your launch.json file (note Unity only appears as an option for the drop down here if you are still in the Settings tab. Navigating back to your code files and trying to do so will not work, but everything shares the same .json file). Hope this helps future devs

**Comment by yaxamie** [comment]
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Unity Editor",
            "type": "unity",
            "path": "PLEASE_ADD_PATH_TO_PROJECT/Library/EditorInstance.json",
            "request": "launch"
        },
        {
            "name": "Windows Player",
            "type": "unity",
            "request": "launch"
        },
        {
            "name": "OSX Player",
            "type": "unity",
            "request": "launch"
        },
        {
            "name": "Linux Player",
            "type": "unity",
            "request": "launch"
        },
        {
            "name": "iOS Player",
            "type": "unity",
            "request": "launch"
        },
        {
            "name": "Android Player",
            "type": "unity",
            "request": "launch"
        },
        {
            "name": "Xbox One Player",
            "type": "unity",
            "request": "launch"
        },
        {
            "name": "PS4 Player",
            "type": "unity",
            "request": "launch"
        },
        {
            "name": "SwitchPlayer",
            "type": "unity",
            "request": "launch"
        }
    ]
}`


I don't know exactly what I did for launch.json back then but... something like the above should work ^^^

It's been wonderful getting comments from fellow frustrated folks over the last year.  Glad to have you guys.
